Add updating instruction
wirenboard/wb-zwave-msw pull request #11
Opened 2022-12-28 08:47 UTC by ekateluv

2022-12-28 08:49 UTC, sikmir approved these changes

2022-12-28 10:47 UTC, webconn approved these changes

2022-12-28 14:38 UTC, ekateluv commented
Ребята, извините что не сделала сразу. Нашла баг в прошивке - на сервер в качестве версии прошивки мсв публиковалась версия минор.патч. Сейчас публикуется мажор.минор. Посмотрите пожалуйста еще раз.

2022-12-29 07:20 UTC, sikmir approved these changes

2022-12-30 07:50 UTC, webconn requested changes

2022-12-30 07:50 UTC, webconn commented on TWBMSWSensor.cpp
> +    memset(semanticVersion, 0, 2);
```suggestion
    uint8_t semanticVersion[2] = {0};
```

2022-12-30 10:31 UTC, merged