Fix update procedure
wirenboard/wb-zwave-msw pull request #14
Opened 2023-01-11 12:43 UTC by ekateluv

### Описание
Поправлена процедура прошивки так, чтобы в качестве единицы данных использовать uint16_t в соответствии с размером модбас-регистров.

### Проверки
- [ ] Проверены все [тест-кейсы](https://github.com/wirenboard/wb-zwave-msw/blob/master/test_cases.md)
- [ ] Поднята версия в файле changelog
- [ ] Поднята версия в определении ZUNO_ENABLE

2023-01-11 12:58 UTC, sikmir commented on WbMsw.ino
> +		SKETCH_VERSION=0x0103
Может тут оставить заглушку, а в Makefile перед сборкой брать версию из changelog и заменять SKETCH_VERSION?

2023-01-11 13:01 UTC, sikmir commented on WbMsw.ino
> +		SKETCH_VERSION=0x0103
А кстати есть ли тулза для дампа прошивки? Чтобы имея бинарник узнать его версию.

2023-01-11 13:08 UTC, sikmir approved these changes

2023-01-11 16:24 UTC, webconn commented on WbMsw.ino
> +		SKETCH_VERSION=0x0103
> Может тут оставить заглушку, а в Makefile перед сборкой брать версию из changelog и заменять SKETCH_VERSION или параметром передавать?

Этим можно будет заняться, раз у нас теперь есть Makefile. Сейчас вместо этого чеклист в шаблоне PR :)

2023-01-12 10:51 UTC, webconn requested changes
И так же везде, где `/ 2` означает приведение к количеству `uint16_t` слов

2023-01-12 10:51 UTC, webconn commented on TFWUpdater.cpp
> +    if (WbMsw->FwUpdate((uint16_t*)WB_MSW_UPDATE_ADDRESS, FirmwareSize / 2)) {
```suggestion
    if (WbMsw->FwUpdate((uint16_t*)WB_MSW_UPDATE_ADDRESS, FirmwareSize / sizeof (uint16_t))) {
```

2023-01-19 11:04 UTC, merged