Add channel Sound Switch
wirenboard/wb-zwave-msw pull request #21
Opened 2023-04-20 07:09 UTC by amatilda

### Описание
_Добавьте описание пул-реквеста_

### Проверки
- [ ] Проверены все [тест-кейсы](https://github.com/wirenboard/wb-zwave-msw/blob/master/test_cases.md)
- [ ] Поднята версия в файле changelog
- [ ] Поднята версия в определении ZUNO_ENABLE

2023-04-20 07:16 UTC, amatilda commented
This is not true for 3.10 version - https://github.com/Z-Wave-Me/Z-Uno-G2-Core

2023-05-10 10:57 UTC, ekateluv requested changes

2023-05-10 10:57 UTC, ekateluv commented on TWBMSWSensor.cpp
> +#define WBMSW_HOLDING_LED_FLASH_TIMOUT 97
TIMEOUT
Лучше назвать PERIOD, поскольку таймаут это по смыслу немного другое

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +static WbMswLedMode_t LedModeSysLed = WB_MSW_LED_MODE_IDLE;
Это нужно выделить в  отдельный класс индикации и убрать все это туда. Это все не нужно помещать в основной файл скетча
В него же нужно убрать поля с хранением состояния светодиодов, которые сейчас находятся в TWBMSWSensor, а в нем оставить только функции чтения-записи по модбасу

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +// Установим нужные типы индикаторов
Вроде решили не писать русских комментариев

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +            WbMsw.SetLedGreenOff();
Сейчас получается, что мы будем включать/выключать светодиоды не в тот момент, когда сменился режим индикации, а вобще при каждом цикле будем устанавливать одни и те же состояния. Это плохо, потому что много ненужного обмена по шине

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +    static uint32_t msLedFreeLast = 0;
Это плохой тон - делать статик переменные внутри функции, тем более когда существуют все возможности сделать класс с полями

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +                msLedFreeLast = msLedCurrent + 2000;
Что делает эта логика?
Если используете числа, выносите в дефайны

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +    (void)freq;
Можно вот так сделать
```
void zunoIndicatorDigitalWrite(uint8_t /*pin*/, uint8_t /*value*/, uint8_t /*indicatorId*/)
{}
```

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +void zunoSysServiceLedSetMode(uint8_t pin, uint8_t mode)
Как я понимаю, это какие то внутренние колбэки (если вам не трудно, напишите когда они вызываются)?
Нужно логику индикации убрать в класс и вызывать методы класса из колбэков

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.h
> +    WB_MSW_LED_MODE_REED = 0x8,
наверное RED

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +        case INDICATOR_ID_ARMED:
Можете пожалуйста дать ссылку на документацию или сказать на словах что обозначают эти константы?

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.h
> +    WB_MSW_LED_MODE_REED_GREEN = (WB_MSW_LED_MODE_GREEN | WB_MSW_LED_MODE_REED),
Когда сделаете enum class можно будет везде убрать одинаковый префикс

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +void zunoIndicatorLoopOpen(uint8_t pin, uint8_t indicatorId)
Считаю, нужно сделать класс для индикации и оставить в нем удобные ручки, которые вызывать внутри системных колбэков

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +    (void)indicatorId;
Зачем эта функция нужна если в ней ничего не происходит?

2023-05-10 10:57 UTC, ekateluv commented on WbMsw.ino
> +                                      ZUNO_SETUP_SOUND_SWITCH_TONE_DURATION_SET(750, 400),
Можете пожалуйста все числа сделать дефайнами, чтобы понимать что все они обозначают

2023-05-10 12:50 UTC, PoltoS commented on WbMsw.ino
> +        case INDICATOR_ID_ARMED:
Это пока только в документации протокола Z-Wave надо смотреть, у нас нет. Это для индикации статусов Armed/Disarmed

2023-05-10 13:00 UTC, amatilda commented on WbMsw.ino
> +                SendTest(0xFFFF);
SendTest - эта функция для теста  в том смысле, что при команде по usb при старте отправит данные по радио.
 0xFFFF - что что пошло не то, а остальное когда версию, что все хорошо

2023-05-10 13:11 UTC, amatilda commented on TZWAVESensor.cpp
> +        if (Channels[i].GetType() == TZWAVEChannel::Type::BUZZER)
С бузерам связан команд класс COMMAND_CLASS_SOUND_SWITCH который не обязан быть в устройстве и который находиться в канале всегда.
Индикатор связан с команд класс COMMAND_CLASS_INDICATOR который обязан всегда быть и он вне каналов. Поэтому они и сбоку хоть и функционал похож.

2023-05-10 13:13 UTC, amatilda commented on TWBMSWSensor.cpp
> +      LedStatusGreen(LedStatus::LED_STATUS_UNKNOWN)
С бузерам связан команд класс COMMAND_CLASS_SOUND_SWITCH который не обязан быть в устройстве и который находиться в канале всегда.
Индикатор связан с команд класс COMMAND_CLASS_INDICATOR который обязан всегда быть и он вне каналов. Поэтому они и сбоку хоть и функционал похож.

2023-05-10 13:14 UTC, amatilda commented on WbMsw.ino
> +                WbMsw.SetLedFlashTimout(1);
Это не настройка каналов - а инициализация устройства в значения по умолчанию.

2023-05-10 13:16 UTC, amatilda commented on WbMsw.ino
> +            WbMsw.SetLedGreenOff();
У сертификации есть требования, а именно при включении и  исключении должно мигать .
Плюс диод раз 10 секунд после последнего мигания пару раз мигает зеленым - что бы понять, что устройство живое

2023-05-10 13:17 UTC, amatilda commented on WbMsw.ino
> +                msLedFreeLast = msLedCurrent + 2000;
диод раз 10 секунд после последнего мигания пару раз мигает зеленым - что бы понять, что устройство живое

2023-05-10 13:19 UTC, amatilda commented on WbMsw.ino
> +void zunoSysServiceLedSetMode(uint8_t pin, uint8_t mode)
zunoSysServiceLedSetMode - это не колбек, а weak функция позволяющая заменить стандартное  мигание диода на свое. Например при включении и исключении устройства

2023-05-10 13:25 UTC, amatilda commented on WbMsw.ino
> +        case INDICATOR_ID_ARMED:
Тут про команд классы
https://sdomembers.z-wavealliance.org/document/dl/917

2023-05-10 13:26 UTC, amatilda commented on WbMsw.ino
> +    (void)indicatorId;
zunoIndicatorDigitalWrite - это заглушка, что бы не пыталась мигать на своих пинах.

2023-05-10 13:41 UTC, ekateluv commented on WbMsw.ino
> +            WbMsw.SetLedGreenOff();
Я тут немного про другое. Вот смотри, у тебя функция ServiceLedLoop вызывается в каждом цикле loop() в состоянии ZUNO_POLL_CHANNELS. В зависимости от скорости это несколько раз в миллисекунду (я точно не знаю, но часто-часто), и каждый раз в зависимости от состояния происходит установка каких то значений для светодиодов, даже если ledMode не изменился. Внутри этого свитча

2023-05-10 13:44 UTC, ekateluv commented on WbMsw.ino
> +                                      ZUNO_SETUP_SOUND_SWITCH_TONE_DURATION_SET(750, 400),
Хорошо, я со значениями не спорю, просто никто не догадается, что это за числа, если не сделать их дефайнами или не написать комментарием, какой в них смысл. Настаиваю все же на дефайнах...
А как подгонять под секуды общую длительность? Напиши об этом комментарий в коде тоже

2023-05-10 13:45 UTC, amatilda commented on WbMsw.ino
> +            WbMsw.SetLedGreenOff();
Да вроде не всегда (во всяком случае покуда я обратного не вижу)- раз в 10 секунд должно зеленым мигать

2023-05-10 14:07 UTC, ekateluv commented on WbMsw.ino
> +                WbMsw.SetLedFlashTimout(1);
Хорошо, предлагаю тогда пока не трогать это место. Сделай сначала индикацию классом, потом посмотрим, как лучше сделать

2023-05-10 14:08 UTC, ekateluv commented on WbMsw.ino
> +            WbMsw.SetLedGreenOff();
Тут не про функционал речь, а про то что по шине одно и то же шлется, если состояние не меняется

2023-05-10 14:29 UTC, amatilda commented on WbMsw.ino
> +            WbMsw.SetLedGreenOff();
Нет там в функции ServiceLedLoop проверка изменилось состояние или нет.
Плюс в SetLedGreenOff и ему подобных должна была быть проверка текущего состояния диода, но почему то в вебе не оказалась - упустил - верней проверка то есть а вот статус где ставит не запушил. Но теперь уже запушил

2023-05-10 15:05 UTC, amatilda commented on WbMsw.ino
> +                SendTest(0xFFFF);
"Могу предположить, что стоит сделать две функции: SendErrorCodeByRadio(...) и SendVersionByRadio(...) и передавать в них код ошибки и версию соответственно." - это чисто для стенда и не более того. Когда шить будем и если устройство не ответила - быстро как должно то это повод призадуматься может что то не так. А если что всегда ресет можно нажать. Другими словами в релезе это вообще не нужно и можно выкинуть.

"Моё субъективное мнение - использование статических переменных внутри функций это порочная практика," - вообще то так и есть)
Но нужно контекст учитывать и я не про то, что функция как временная и можно выкинуть ее.
А про то, что данная функция вне класса и даже не подразумевает использования с нескольких потоков.
Можно конечно обернуть ее в класс и тем самым для каждого класса будет свое состояние. Но  каждую функцию запихивать в класс такое себе. Да и других моментов много, в том что  это все таки чип а не компьютер и ресурсы тут все же ограничены зачастую.

2023-05-10 21:53 UTC, PoltoS commented on TWBMSWSensor.cpp
> +      LedStatusGreen(LedStatus::LED_STATUS_UNKNOWN)
В отличии от температуры, статусы светодиодов - это наши сущности, отсутствующие в вашем чипе. Вам мы передаём время мигания. Из времени назад статус получать неудобно. Поэтому нам надо их хранить.

2023-05-11 07:55 UTC, ekateluv commented on WbMsw.ino
> +                SendTest(0xFFFF);
"Другими словами в релезе это вообще не нужно и можно выкинуть" - а зачем тогда это вливать в мастер репозитория, мы на своей стороне шьем  эту прошивку как есть...
Напиши об этом хотя бы комментарий, потому что мы потом не поймем для чего это. В идеале - лучше чтобы это было сделано через дефайн тестирования, по типу как DEBUG

2023-05-11 08:02 UTC, amatilda commented on WbMsw.ino
> +                SendTest(0xFFFF);
Комментарий добавлю.
А дефайн  не рискну добавить - я уже пытался через дефайн  текст временный оформить.

2023-05-11 09:15 UTC, ekateluv approved these changes

2023-05-11 09:28 UTC, webconn commented
Решили не исправлять сейчас все стилистические моменты, чтобы сейчас перейти к тестированию

2023-05-11 09:45 UTC, PoltoS commented on WbMsw.ino
> +                SendTest(0xFFFF);
Разве это не для производственного теста? @amatilda это нужно оставить в финальном коде?

2023-05-11 11:22 UTC, sikmir commented on TWBMSWSensor.cpp
> +#define WBMSW_COLI_LED_GREEN 11
```suggestion
#define WBMSW_COIL_LED_RED 10
#define WBMSW_COIL_LED_GREEN 11
```

2023-05-11 11:26 UTC, sikmir commented on TWBMSWSensor.cpp
> +bool TWBMSWSensor::BuzzerAviable(TWBMSWSensor::Availability& availability)
```suggestion
bool TWBMSWSensor::BuzzerAvailable(TWBMSWSensor::Availability& availability)
```

2023-05-11 11:45 UTC, sikmir commented on WbMsw.ino
> +        if (SoundSwitchStateOld == true) {
```suggestion
        if (SoundSwitchStateOld) {

```

2023-05-11 11:48 UTC, sikmir commented on debian/changelog
> +wb-zwave-msw (1.10) stable; urgency=medium
Тут надо оставить только один релиз.

2023-05-16 12:59 UTC, merged