fix agi
wirenboard/wb-zwave-msw pull request #27
Opened 2023-09-04 08:50 UTC by amatilda

### Описание
_Добавьте описание пул-реквеста_

### Проверки
- [ ] Проверены все [тест-кейсы](https://github.com/wirenboard/wb-zwave-msw/blob/master/test_cases.md)
- [ ] Поднята версия в файле changelog
- [ ] Поднята версия в определении ZUNO_ENABLE

2023-09-06 09:16 UTC, ekateluv requested changes
Пожалуйста, напишите описание того, что вы тут изменили

2023-09-06 09:16 UTC, ekateluv commented on TZWAVEChannel.cpp
> +        return (true);
```suggestion
        return true;
```

2023-09-06 09:16 UTC, ekateluv commented on TZWAVESensor.cpp
> +    // DEBUG("--------------------Measurements-----------------------\n");
Так и должно быть закомменченым?

2023-09-06 09:16 UTC, ekateluv commented on debian/changelog
> + -- Ekaterina Volkova <ekaterina.volkova@wirenboard.ru>  Fri, 16 Dec 2022 12:50:42 +0300
Что здесь исправлено? Отсутствует новая запись о ваших изменениях.

2023-09-07 21:44 UTC, amatilda commented
fix agi - исправлен профиль для ассоциаций.
for fast loop - раньше в функции loop был delay(50) теперь delay(2) 
del duplicate - удален дублирующий define
melodies update - обновлены мелодии по количеству и длительности
added sensor polling frequency - добавлена задержка для опроса датчиков

2023-09-07 21:45 UTC, amatilda commented on TZWAVESensor.cpp
> +    // DEBUG("--------------------Measurements-----------------------\n");
Иначе спамит каждых 20 - 100 мс

2023-09-07 21:45 UTC, amatilda commented on debian/changelog
> + -- Ekaterina Volkova <ekaterina.volkova@wirenboard.ru>  Fri, 16 Dec 2022 12:50:42 +0300
fix agi - исправлен профиль для ассоциаций.
for fast loop - раньше в функции loop был delay(50) теперь delay(2)
del duplicate - удален дублирующий define
melodies update - обновлены мелодии по количеству и длительности
added sensor polling frequency - добавлена задержка для опроса датчиков

2023-09-08 10:45 UTC, ekateluv commented on debian/changelog
> + -- Ekaterina Volkova <ekaterina.volkova@wirenboard.ru>  Fri, 16 Dec 2022 12:50:42 +0300
Информацию о ваших изменениях нужно написать в changelog

2023-09-08 10:46 UTC, ekateluv commented on TZWAVESensor.cpp
> +    // DEBUG("--------------------Measurements-----------------------\n");
Если хочется отключить дебаг вывод нужно просто убрать определение из ZUNO_ENABLE вроде

2023-09-14 12:56 UTC, amatilda commented on TZWAVESensor.cpp
> +    // DEBUG("--------------------Measurements-----------------------\n");
Если отключить дебаг вывод то все верно, но если нужно убрать то что спамит, то это не поможет

2025-01-24 15:49 UTC, closed without merging