Scan modbus address
wirenboard/wb-zwave-msw pull request #3
Opened 2022-10-27 09:19 UTC by ekateluv

Поиск перебором адреса msw. Немного изменила поведение: при ошибке устройство не висит по while(1) в стартапе, а работает по свич-кейсу в loop(). Передача объекта датчика через указатель.
Коммитов получилось много, но все маленькие, много чисто с форматированием.

2022-10-27 09:53 UTC, webconn commented on TWBMSWSensor.cpp
> +void TWBMSWSensor::SetModbusAddress(uint16_t Address)
А зачем аргументы с большой буквы начинать? У нас в [кодстайле](https://github.com/wirenboard/codestyle/blob/master/C%2B%2B.ru.md) вроде не так, и это только больше сложностей сделало

2022-10-27 09:53 UTC, webconn commented on TWBMSWSensor.cpp
> +	delay(TimeoutMs);
Глядя на определение метода, я бы решил, что `TimeoutMs` - это время, через которое метод вернётся в любом случае, а тут это время ожидания готовности устройства, судя по всему. То есть, по смыслу больше подходит слово delay (`flash_ready_delay` или что-то такое).

А в идеале вообще избавиться бы от этого места в пользу поллинга какого-нибудь флага

2022-10-27 09:53 UTC, webconn commented on WbMsw.ino
> +	switch (ZUnoState)
А я правильно понимаю, что если что-то ломается, то мы будем постоянно посылать сообщение об ошибке раз в секунду, не пытаясь восстановить соединение? Быстрый поиск по коду показал, что `ZUnoState` меняется только в `setup()`

2022-10-27 10:01 UTC, ekateluv commented on WbMsw.ino
> +	switch (ZUnoState)
Да. Раньше оно делало +- то же, только сидело в setup при ошибке. Какую логику вместо этой ты хотел бы видеть?

2022-10-27 10:11 UTC, webconn commented on WbMsw.ino
> +	switch (ZUnoState)
Ну можно было бы пробовать переподключиться к датчику, например, если это имеет смысл в контексте ошибки. А так `while(1)` в том месте, где случилась ошибка без возможности восстановления, в МК нормальная практика. Я вот, читая код, подумал, что раз это в loop, значит, можно восстановиться и однажды выполнение пойдёт по другой ветке свитча

2022-10-27 12:20 UTC, ekateluv commented on TWBMSWSensor.cpp
> +	delay(TimeoutMs);
После того, как устаналивается 1 в регистр для обновления прошивки, устройство перезапускается, запускается загрузчик, после запуска он ждет 2 минуты получения новой прошивки. Спросить устройство, в загрузчике ли оно и ожидает ли прошивку, возможности нет. Только подождать.

2022-10-27 12:35 UTC, ekateluv commented on WbMsw.ino
> +	switch (ZUnoState)
Фактически сейчас три ошибки может быть: не открылся порт, не найден чип мсв, не может получить нужные значения из регистров. Все три мне не кажутся супер-критичными, в каждой можно продолжать пытаться.

2022-10-27 13:15 UTC, webconn commented on WbMsw.ino
> +	switch (ZUnoState)
Давай попробуем сделать восстановление. Удобно ж

2022-10-28 10:54 UTC, KraPete commented
1. Надо инструкцию по сборке. Или Makefile или скрипты. Сейчас новый человек придёт и хз как собирать.
2. Почему стало  странное форматирование, скобочки с новой строки?
было
```
} else {
```
стало
```

2022-10-28 10:57 UTC, KraPete commented
3. Вернулись к глобальному объекту. Может, и передачу его по указателю уберём? Да, это идеологически криво, но так мы сильно уменьшим число изменений в коде.

2022-10-28 11:00 UTC, KraPete commented
Ну или по ссылке передавать?

2022-11-07 12:39 UTC, ekateluv commented
> 3. Вернулись к глобальному объекту. Может, и передачу его по указателю уберём? Да, это идеологически криво, но так мы сильно уменьшим число изменений в коде.

Давай по ссылке тогда. Есть вероятность, что все эти функции с каналами позднее в отдельный файл перекинем, тогда в любом случае придется избавляться от глобальности. Пока точно сказать не могу, но код уже выглядит как нагромождение(

2022-11-07 12:57 UTC, ekateluv commented
> 3. Вернулись к глобальному объекту. Может, и передачу его по указателю уберём? Да, это идеологически криво, но так мы сильно уменьшим число изменений в коде.

Так а вроде нет цели уменьшать количество изменений...Сделаю тогда передачу по ссылке лучше. Вдруг выделим все эти функции в отдельный файл, а то там и так уже нагромождение кода в основном скрипте

2022-11-14 07:51 UTC, webconn requested changes

2022-11-14 07:51 UTC, webconn commented on TFastModbus.cpp
> +            timeout = timeout - 0xA;
Не понимаю я, зачем использовать hex для констант с задержками

2022-11-14 07:51 UTC, webconn commented on TFastModbus.cpp
> +            delay(0xA);
Стоит `10` вынести в отдельную константу хоть внутри функции, раз уж она повторяется.

2022-11-14 07:51 UTC, webconn commented on TFastModbus.cpp
> +bool TFastModbus::OpenPort(size_t Speed, uint32_t Config, uint8_t Rx, uint8_t Tx)
Аргументы с маленькой буквы

2022-11-14 07:51 UTC, webconn commented on TWBMSWSensor.cpp
> +    count = 0x0;
Константы смешные все (где `0x0`, где `0`, а тут ещё и `00` встретилось).

И почему их нельзя было в объявление переменных положить? Они ж локальные все. А ещё тут вроде С++, не С89, переменные можно где угодно объявить

2022-11-14 07:51 UTC, webconn commented on TWBMSWSensor.cpp
> +            number = number * 0xA + (letter - 0x30);
Умножать на 10 как-то понятней, чем на 0xA. А ещё `0x30` - магия, обычно пишут `letter - '0'`

2022-11-14 07:51 UTC, webconn commented on TWBMSWSensor.cpp
> +#ifdef LOGGING_DBG
В какой-то момент это стало тяжеловато читать.

Надо куда-нибудь в заголовок вписать

```cpp
#ifdef LOGGING_DBG
#define DEBUG LOGGING_UART.print
#else
#define DEBUG(...) ((void) 0)
#endif
```

и потом везде писать `DEBUG(...)` без оборачивания

2022-11-14 07:51 UTC, webconn commented on TWBMSWSensor.cpp
> +    LOGGING_UART.print("Wait 2 sec\n");
Про 2 секунды потенциально неправда же

2022-11-15 05:29 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    count = 0x0;
Потому что это не мой код на самом деле) Я переименовала файл, и теперь кажется будто я это написала. Но я исправлю

2022-11-15 06:44 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    count = 0x0;
`0x0` выглядит как мордочка, кстати

2022-11-15 07:37 UTC, ekateluv commented on TFastModbus.h
> +    void ClosePort(void);
Объект быстрого модбаса глобальный в скрипте, он есть пока запущен скрипт. При этом после сканирования по быстрому модбасу мне нужно закрыть порт, чтобы простой модбас мог его корректно открыть

2022-11-15 12:18 UTC, ekateluv commented on TFastModbus.cpp
> +            timeout = timeout - 0xA;
Убрала в define

2022-11-15 12:18 UTC, ekateluv commented on TFastModbus.cpp
> +            delay(0xA);
Убрала

2022-11-15 12:18 UTC, ekateluv commented on TFastModbus.cpp
> +bool TFastModbus::OpenPort(size_t Speed, uint32_t Config, uint8_t Rx, uint8_t Tx)
Поправила

2022-11-15 12:19 UTC, ekateluv commented on TWBMSWSensor.cpp
> +            number = number * 0xA + (letter - 0x30);
Исправлено

2022-11-15 12:19 UTC, ekateluv commented on TWBMSWSensor.cpp
> +#ifdef LOGGING_DBG
Добавила отдельный файл с дефайнами для отладки

2022-11-15 12:19 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    LOGGING_UART.print("Wait 2 sec\n");
Поправила на вывод реального значения

2022-11-15 12:20 UTC, ekateluv commented on TWBMSWSensor.cpp
> +	if (!ModBusRtuClass::begin(Speed, Config, Rx, Tx))
Поправлено

2022-11-15 12:20 UTC, ekateluv commented on TFastModbus.cpp
> +            timeout = timeout - 0xA;
Поправлено

2022-11-15 12:20 UTC, ekateluv commented on TFastModbus.cpp
> +            for (int i = 0; i < availableDataLength; i++) {
написала проверку

2022-11-15 12:21 UTC, ekateluv commented on TFastModbus.cpp
> +        memcpy(serialNumber, newSerialNumber, WB_MSW_SERIAL_NUMBER_SIZE);
Сделала проверку длин в начале функции

2022-11-15 12:22 UTC, ekateluv commented on TFastModbus.cpp
> +bool TFastModbus::ContinueScan(uint8_t* serialNumber, uint8_t* modbusAddress)
Сделала комментарии с описанием формата пакета, что обозначают числа написано

2022-11-16 05:31 UTC, webconn commented on TFastModbus.cpp
> +    }
```suggestion
    if (!result) {
         DEBUG("*** ERROR Sending fast modbus scan start!\n");
         return false;
     }

     delay(Serial->countWaitingMs(4));
     return true;
```

И кстати, зачем тут delay?

2022-11-16 05:40 UTC, webconn commented on TFastModbus.cpp
> +            // If fast modbus subcommand==0x04, there are no unsolicited devices left on fast modbus bus
`unsolicited` - а это слово точно из нашего контекста? А то [интернеты говорят](https://context.reverso.net/%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4/%D0%B0%D0%BD%D0%B3%D0%BB%D0%B8%D0%B9%D1%81%D0%BA%D0%B8%D0%B9-%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9/unsolicited), что оно скорее означает "нежелательный", чем "неопрошенный".

```suggestion
            // subcommand 0x04 means that scan is finished
```

2022-11-16 05:49 UTC, webconn commented on WbMsw.ino
> +// LOGGING_UART.println("--------------------Measurements-----------------------");
Теперь тут можно обойтись `DEBUG()`. Вообще советую погрепать исходники на предмет старых `ifdef`

2022-11-16 07:59 UTC, ekateluv commented on TFastModbus.cpp
> +    }
Потому что модбас требует чтобы между пакетами был промежуток времени на 3,5 символа. Соответственно, если отправка не удалась, то можно не ждать: все равно ответа не будет.

2022-11-16 08:01 UTC, ekateluv commented on DebugOutput.h
> +#define LOG_FIXEDPOINT_VALUE(TEXT, VALUE, PREC)
Если нам не нравится код авторства zwave, может стоит полноценный рефакторинг устроить? Это код тоже не мой, я только переместила все дебаговые дефайны в отдельный файл.

2022-12-05 10:50 UTC, closed without merging