Refactoring
wirenboard/wb-zwave-msw pull request #5
Opened 2022-11-23 14:14 UTC by ekateluv

2022-11-24 07:33 UTC, webconn requested changes

2022-11-24 07:33 UTC, webconn commented on TFastModbus.cpp
> +#define TIMEOUT_COUNTING_DELTA 10
Это ж микроконтроллер, разве он сильно расстроится из-за того, что мы заблокируемся хоть с busy-loop? Если эту дельту сделать 1 мс, тогда мы раньше узнаем о приходе данных и при этом при введённом таймауте 19 не получим на самом деле 10

2022-11-24 07:33 UTC, webconn commented on TWBMSWSensor.cpp
>          } else {
Кстати, я тут понял, что у этой штуки будут проблемы с чтением версий с суффиксами (по-моему, мы их уже практикуем):
https://intwiki.contactless.ru/dokuwiki/doku.php?id=soft:periph-versioning

Но я бы это в следующем PR решил. Возможно, вообще отказом от хранения версии как `int32` и использования вместо этого `char[]`, как положено

2022-11-24 07:33 UTC, webconn commented on TWBMSWSensor.cpp
> +    version[0] = out;
```suggestion
    *version = out;
```
А то кажется, что тут массив

2022-11-24 07:33 UTC, webconn commented on TZWAVEChannel.cpp
> +void TZWAVEChannel::SetTemperatureChannel(enum TZWAVEChannelType type,
Не до конца понятно, зачем в этом и последующих методах мы принимаем `type` как аргумент, если тип уже закодирован в имени метода. Ничего не помешает сделать

```c
SetTemperatureChannel(TZWAVEChannelType::WB_MSW_CHANNEL_TYPE_HUMIDITY, ...)
```

2022-11-24 07:33 UTC, webconn commented on TZWAVEChannel.h
> +    // field
...и тем самым сводится на нет вся попытка устроить инкапсуляцию.

```c
void* GetValuePointer() {
  switch (type) {
    case TZWAVEChannelType::WB_MSW_CHANNEL_TYPE_TEMPERATURE:
      return static_cast<void*>(&Temperature);
    ...
  }
}
```

А на практике даже этот свитч внутри должен будет соптимизироваться компилятором в возврат одного и того же указателя во всех случаях (хотя только в С++14 гарантируется, что указатель будет одним и тем же).

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +        switch (Channels[i].GetType()) {
Если сделать `GetValuePointer()` в `TZWAVEChannel`, то этот `switch` будет не нужен

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +    if (ZUNO_CFG_CHANNEL_COUNT > 1)
Скобки

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +    for (uint8_t i = 0; i < ZUNO_CFG_CHANNEL_COUNT; i++)
Скобки

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +    if (paramNumber < WB_MSW_CONFIG_PARAMETER_FIRST || paramNumber > WB_MSW_CONFIG_PARAMETER_LAST) {
Тут никакой `debug` добавить не надо?

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +    if (paramNumber < WB_MSW_CONFIG_PARAMETER_FIRST || paramNumber > WB_MSW_CONFIG_PARAMETER_LAST) {
Тоже дебаг

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +{
Вылетим за границу массива?

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +        if (Channels[i].GetType() == type)
Скобки везде

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +    return 0;
```suggestion
    return NULL;
```

2022-11-24 07:33 UTC, webconn commented on TZWAVESensor.cpp
> +            if (!GetChannelByType(TZWAVEChannelType::WB_MSW_CHANNEL_TYPE_TEMPERATURE))
Скобки. Пишу в последний раз, советую натравить clang-tidy

2022-11-24 08:41 UTC, ekateluv commented on TZWAVEChannel.cpp
> +void TZWAVEChannel::SetTemperatureChannel(enum TZWAVEChannelType type,
Да, выглядит не очень. 
Можно например убрать этот аргумент и присваивать тип внутри функции. Либо можно вообще сделать одну функцию ```ChannelSetup()```с передачей типа. Правда, есть отличия в последнем аргументе, который инициализирует значение (в зависимости от типа канала, мы можем передавать тип uint16_t, uint32_t, uint8_t). Можно например оставить в аргументе самый большой тип uint32_t и потом приводить к нужному типу внутри.

2022-11-24 09:05 UTC, ekateluv commented on TZWAVEChannel.h
> +    // field
```cpp
void TZWAVESensor::SetChannelHandlers()
{
    for (size_t i = 0; i < ChannelsCount; i++)
        switch (Channels[i].GetType()) {
            case TZWAVEChannelType::WB_MSW_CHANNEL_TYPE_TEMPERATURE:
                zunoAppendChannelHandler(i,
                                         WB_MSW_INPUT_REG_TEMPERATURE_VALUE_SIZE,
                                         CHANNEL_HANDLER_SINGLE_VALUEMAPPER,
                                         (void*)&Channels[i].Temperature);
```
Вот эта функция, в случае указания CHANNEL_HANDLER_SINGLE_VALUEMAPPER, мне вообще в принципе не даст в качестве последнего аргумента указать что-либо кроме ссылки на переменную, из которой берется значение, оно даже не соберется если туда поставить ссылку на функцию.
Можно еще попробовать изменить тип (например CHANNEL_HANDLER_SINGLE_GETTER), там можно указать ссылку на функцию. Правда, не могу быть уверена, что примется ссылка на метод класса, а не на просто функцию.
[https://z-uno.z-wave.me/Reference/zunoAppendChannelHandler/](url) Можно будет поэкспериментировать с этим местом

2022-11-24 09:09 UTC, webconn commented on TZWAVEChannel.h
> +    // field
Так ты не ссылку на функцию ставь, а возвращаемое значение

2022-11-24 09:10 UTC, webconn commented on TZWAVEChannel.cpp
> +void TZWAVEChannel::SetTemperatureChannel(enum TZWAVEChannelType type,
В С++ есть перегрузка функций по аргументу, но вообще тебе больше подходит первый вариант (с присваиванием типа внутри)

2022-12-01 14:53 UTC, ekateluv commented on TZWAVESensor.cpp
> +            if (!GetChannelByType(TZWAVEChannelType::WB_MSW_CHANNEL_TYPE_TEMPERATURE))
поправлено

2022-12-01 14:53 UTC, ekateluv commented on TZWAVESensor.cpp
> +    return 0;
поправлено

2022-12-01 14:53 UTC, ekateluv commented on TZWAVESensor.cpp
> +        if (Channels[i].GetType() == type)
поправлено

2022-12-01 14:53 UTC, ekateluv commented on TZWAVESensor.cpp
> +{
добавила проверку

2022-12-01 14:54 UTC, ekateluv commented on TZWAVESensor.cpp
> +    if (paramNumber < WB_MSW_CONFIG_PARAMETER_FIRST || paramNumber > WB_MSW_CONFIG_PARAMETER_LAST) {
дописала

2022-12-01 14:54 UTC, ekateluv commented on TZWAVESensor.cpp
> +    for (uint8_t i = 0; i < ZUNO_CFG_CHANNEL_COUNT; i++)
добавила

2022-12-01 14:54 UTC, ekateluv commented on TZWAVESensor.cpp
> +    if (ZUNO_CFG_CHANNEL_COUNT > 1)
добавила

2022-12-01 14:54 UTC, ekateluv commented on TZWAVESensor.cpp
> +        switch (Channels[i].GetType()) {
Сделала

2022-12-01 14:54 UTC, ekateluv commented on TZWAVEChannel.h
> +    // field
сделала

2022-12-01 14:54 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    version[0] = out;
поправлено

2022-12-01 14:54 UTC, ekateluv commented on TFastModbus.cpp
> +#define TIMEOUT_COUNTING_DELTA 10
сделала 1

2022-12-01 14:57 UTC, ekateluv commented
Я добавила отладочный вывод. Правда его стало настолько много, что читать лог в реальном времени стало трудно. Поэтому закомментировала, если нужно будет для отладки, то просто расскоментировать и все.

2022-12-02 03:58 UTC, webconn requested changes

2022-12-02 03:58 UTC, webconn commented on TZWAVEChannel.h
> +    // field
Коммент по итогу остался лишним

2022-12-02 03:58 UTC, webconn commented on TZWAVEChannel.cpp
> +            break;
`break` не нужен, если до него был `return`, тут ведь уже такое встречалось

2022-12-02 03:58 UTC, webconn commented on WbMsw.ino
> +    ZwaveSensor.GetGroupNameByIndex(groupIndex);
`return` не хватает? Проект без `-Wall -Werror` собирается?

2022-12-02 03:58 UTC, webconn commented on WbMsw.ino
> +    ZwaveSensor.GetParameterIfChannelExists(paramNumber);
тоже `return`?

2022-12-02 04:48 UTC, webconn commented
А приложи сюда ещё инструкцию по сборке, пожалуйста. И тест-кейсы

2022-12-05 06:44 UTC, webconn commented
```
[Starting] Verify sketch - WbMsw.ino
          ***** Building sketch:/home/webconn/dev/wb/wb-zwave-msw/WbMsw.ino *****
          -----------------------------------------------------------------------------------------------

preprocessing "WbMsw.ino"                ..............................
preprocessing "WbMsw.ino"                ..............................                            OK
          Core version: 03.07 Channels:0

Gathering project files                  ..............................
Gathering project files                  ..............................                            OK

compiling "WBMSWSensor.cpp"              ..............................
compiling "WBMSWSensor.cpp"              ..............................                        FAILED
          In file included from /home/webconn/dev/wb/wb-zwave-msw/WBMSWSensor.cpp:2:0:
          /home/webconn/dev/wb/wb-zwave-msw/WBMSWSensor.h:4:10: fatal error: ModBusRtu.h: No such file or directory
           #include "ModBusRtu.h"
                    ^~~~~~~~~~~~~
          compilation terminated.
```

Кажется, тут чего-то не хватает

2022-12-05 07:51 UTC, webconn commented
> Кажется, тут чего-то не хватает

Это я оказался невнимательным, забыл выбрать Z-Uno Beta (3.0.9)

2022-12-05 08:10 UTC, webconn commented on TZWAVEChannel.cpp
> +    }
А что в случае ошибки вернётся? Так ведь нельзя

2022-12-05 08:10 UTC, webconn commented on test_cases.md
> +6. устройство исключается из интерфейса севера;
```suggestion
6. устройство исключается из интерфейса сервера;
```

А что это значит? Что-то вроде "можно удалить устройство из интерфейса"? Это подразумевает какое-то взаимодействие с нашим датчиком?

2022-12-05 08:10 UTC, webconn commented on test_cases.md
> +#Тест-кейсы
Сюда надо ещё дописать, какое поведение ожидается, если перезагрузится контроллер на MSW или z-wave модуль

2022-12-05 08:41 UTC, ekateluv commented on test_cases.md
> +6. устройство исключается из интерфейса севера;
Да, процедура добавления и исключения любого z-wave устройства одинакова: нужно 3 раза быстро нажать на кнопочку. Надо проверять что оно нормально добавляется и исключается

2022-12-05 08:44 UTC, webconn commented on test_cases.md
> +6. устройство исключается из интерфейса севера;
Надо дописать тогда про процедуру, а то неочевидно

2022-12-05 10:02 UTC, ekateluv commented on TZWAVEChannel.cpp
> +    }
сделала return 0

2022-12-05 10:04 UTC, webconn commented on test_cases.md
> +8. устройство исключается из интерфейса севера;
Ну допиши сюда про три нажатия кнопочки :)

2022-12-05 10:40 UTC, webconn approved these changes

2022-12-05 10:50 UTC, merged