Add build and flash instrustion
wirenboard/wb-zwave-msw pull request #7
Opened 2022-12-16 09:05 UTC by ekateluv

2022-12-16 13:29 UTC, webconn requested changes
На самом деле дока получилась хорошая и обстоятельная. Если с правками согласна, можешь прям гитхабом их батчем добавить. Но чеклист для PR предлагаю здесь же сделать

2022-12-16 13:29 UTC, webconn commented on README.md
> +**${clang_path}** - путь к библиотеке clang
```suggestion
 * `${file}` - .ino файл проекта (скетч, должен быть в проекте один)
 * `${core_path}` - путь к папке с core-файлами
 * `${arm_gcc_path}` -  путь к arm-gcc
 * `${tmp_path}` - временная директория для файлов сборки
 * `${clang_path}` - путь к библиотеке clang
```

Чуть более аккуратный markdown получится, а то список не выводится:
![image](https://user-images.githubusercontent.com/1550335/208107257-203c91ec-7acb-4324-8792-e033399569e3.png)

2022-12-16 13:29 UTC, webconn commented on README.md
> +Перед первой прошивкой модуля необходимо в первую очередь обновить [бутлодер](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/tree/master/hardware/arduino/zunoG2/bootloaders), файл **zuno_bootloader_HW070
> HW0704.bin

Эта версия не устареет в скором времени?

```suggestion
Перед первой прошивкой модуля необходимо в первую очередь обновить [бутлодер](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/tree/master/hardware/arduino/zunoG2/bootloaders), файл **zuno_bootloader_HW0704.bin** или более новый. Обновление бутлодера выполняется командой 
```

2022-12-16 13:29 UTC, webconn commented on README.md
> +Для дальнейшей работы с модулем потребуется запомнить **S2 PIN**, так как он нужен для добавления устройства в сервер. В разделе **DEVICE CFG** можно увидеть текущий режим защиты, частоту, мощность р
> 16сс

Никогда не встречал такого сокращеня

```suggestion
Для дальнейшей работы с модулем потребуется запомнить **S2 PIN**, так как он нужен для добавления устройства в сервер. В разделе **DEVICE CFG** можно увидеть текущий режим защиты, частоту, мощность радиосигнала (выводится в hex). 
```

2022-12-19 05:52 UTC, KraPete approved these changes

2022-12-21 08:25 UTC, webconn commented on .github/pull_request_template.md
> +- [ ] Проверены все тест-кейсы
Давай ещё ссылку на тесткейсы

2022-12-21 08:25 UTC, webconn commented on README.md
> +Если прошивка осуществляется в автоматическом режиме, то необходимо задать режим шифрования (включено), частоту (7 - RU, 0 - EU) и мощность радиосигнала в децибеллах(число интерпретируется как десяти
Тут не про `dBm` идёт речь? И хочется примеров, что такое много и мало (например, что там стояло, когда тебе приходилось датчик в нескольких сантиметрах держать)

2022-12-21 08:28 UTC, webconn commented on README.md
> +Если прошивка осуществляется в автоматическом режиме, то необходимо задать режим шифрования (включено), частоту (7 - RU, 0 - EU) и мощность радиосигнала в децибеллах(число интерпретируется как десяти
Добавлю, я не знаток радио, просто решил уточнить

2022-12-23 06:37 UTC, webconn commented on README.md
> +Если прошивка осуществляется в автоматическом режиме, то необходимо задать режим шифрования (включено), частоту (7 - RU, 0 - EU) и мощность радиосигнала в децибеллах(число интерпретируется как десяти
Ты прям проверила, что это `dBm`, или просто за мной повторила? :)
И тут всё ещё не хватает инфы о том, что 20 - это рекомендуемое значение

2022-12-23 06:38 UTC, webconn commented on README.md
> +Если прошивка осуществляется в автоматическом режиме, то необходимо задать режим шифрования (включено), частоту (7 - RU, 0 - EU) и мощность радиосигнала в децибеллах(число интерпретируется как десяти
И кстати, это не про то же?

![image](https://user-images.githubusercontent.com/1550335/209285071-d2042821-02df-4abc-96f5-54af1a56ea4b.png)

2022-12-23 14:47 UTC, ekateluv commented on README.md
> +Если прошивка осуществляется в автоматическом режиме, то необходимо задать режим шифрования (включено), частоту (7 - RU, 0 - EU) и мощность радиосигнала в децибеллах(число интерпретируется как десяти
Да, это то же самое, обозначение dBm написано в самом VSCode. +2.0 это то же самое что -p main_pow=20 
![Снимок экрана от 2022-12-23 17-45-27](https://user-images.githubusercontent.com/97599621/209354365-a33cd9e1-6af2-4135-9e41-f6c781a9b01e.png)
Вроде написала все...

2022-12-26 07:06 UTC, webconn commented on README.md
> +Если прошивка осуществляется в автоматическом режиме, то необходимо задать режим шифрования (включено), частоту (7 - RU, 0 - EU) и мощность радиосигнала в децибеллах(число интерпретируется как десяти
Так 20 и 2.0 - это разные числа

2022-12-26 08:13 UTC, sikmir commented on .github/pull_request_template.md
> +- [ ] Проверены все [тест-кейсы]([https://github.com/wirenboard/wb-zwave-msw/blob/master/test_cases.md)
```suggestion
- [ ] Проверены все [тест-кейсы](https://github.com/wirenboard/wb-zwave-msw/blob/master/test_cases.md)
```

2022-12-26 08:15 UTC, sikmir commented on README.md
> +Для автоматической сборки проекта поребуется скачать [Z-Uno-G2-Core](https://github.com/Z-Wave-Me/Z-Uno-G2-Core), [GCC](http://rus.z-wave.me/files/z-uno/g2/tc//arm-none-eabi-gcc-7_2_4-linux64.tar.gz)
```suggestion
Для автоматической сборки проекта поребуется скачать [Z-Uno-G2-Core](https://github.com/Z-Wave-Me/Z-Uno-G2-Core), [GCC](http://rus.z-wave.me/files/z-uno/g2/tc//arm-none-eabi-gcc-7_2_4-linux64.tar.gz) и [CLANG](http://rus.z-wave.me/files/z-uno/g2/tc/libclang_11_0_1-linux64.tar.gz).
```

2022-12-26 08:15 UTC, sikmir commented on README.md
> +Для автоматической сборки проекта поребуется скачать [Z-Uno-G2-Core](https://github.com/Z-Wave-Me/Z-Uno-G2-Core), [GCC](http://rus.z-wave.me/files/z-uno/g2/tc//arm-none-eabi-gcc-7_2_4-linux64.tar.gz)
```suggestion
Для автоматической сборки проекта поребуется скачать [Z-Uno-G2-Core](https://github.com/Z-Wave-Me/Z-Uno-G2-Core), [GCC](http://rus.z-wave.me/files/z-uno/g2/tc//arm-none-eabi-gcc-7_2_4-linux64.tar.gz) и [CLANG](http://rus.z-wave.me/files/z-uno/g2/tc/libclang_11_0_1-linux64.tar.gz).
```

2022-12-26 08:17 UTC, sikmir commented on README.md
> +Основным инструментом для сборки и настройки является утилита **zme_make**, доступная в [архиве с инструментами](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/tree/master/toolchain/linux64), а также в р
```suggestion
Основным инструментом для сборки и настройки является утилита **zme_make**, доступная в [архиве с инструментами](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/tree/master/toolchain/linux64), а также в `/Z-Uno2 (Beta)/tools/zme_make` в папке с ZUNO-компонентами при установке расширения ZUNO в VSCode.
```

2022-12-26 08:19 UTC, sikmir commented on README.md
> +### Настройка сборки VSCode
```suggestion
### Настройка сборки в VSCode
```

2022-12-26 08:22 UTC, sikmir commented on README.md
> +:warning: **Версия SDK**:иногда при обновлении SDK из его старых версий могут уехать нужные библиотеки. Поэтому, если вы вдруг установили 3.0.9, но нужных библиотек нет, проверьте, не была ли выпущен
```suggestion

:warning: **Версия SDK**: иногда при обновлении SDK из его старых версий могут уехать нужные библиотеки. Поэтому, если вы вдруг установили 3.0.9, но нужных библиотек нет, проверьте, не была ли выпущена новая версия.
```

2022-12-26 08:23 UTC, sikmir commented on README.md
> +Также в статус-баре можно выбрать тип платы (должен быть Z-Uno2(Beta)) и последовательный порт. Для того, чтобы собрать и прошить проект, нужно открыть основной файл ***.ino** и в верней панели нажат
```suggestion
Также в статус-баре можно выбрать тип платы (должен быть Z-Uno2(Beta)) и последовательный порт. Для того, чтобы собрать и прошить проект, нужно открыть основной файл ***.ino** и в верхней панели нажать кнопку **"Загрузить"**.
```

2022-12-26 08:25 UTC, sikmir commented on README.md
> +```
```suggestion
```sh
zme_make build  ${file} \
  -S ${core_path}/Z-Uno-G2-Core/hardware/arduino/zunoG2/cores/ \
  -S ${core_path}/Z-Uno-G2-Core/hardware/arduino/zunoG2/libraries \
  -S ${arm_gcc_path}/lib/gcc/arm-none-eabi/7.2.1/include/ \
  -B ${tmp_path} -T ${arm_gcc_path}/bin/ -lc ${clang_path} \
  -O make_listing -O BO:-DARDUINO=152 \
  -O BO:-DARDUINO_ARCH_ZUNOG2
```
```

2022-12-26 08:26 UTC, sikmir commented on README.md
> +Перед первой прошивкой модуля необходимо в первую очередь обновить [бутлодер](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/tree/master/hardware/arduino/zunoG2/bootloaders).Рекомендуется выполнять загру
```suggestion
Перед первой прошивкой модуля необходимо в первую очередь обновить [бутлодер](https://github.com/Z-Wave-Me/Z-Uno-G2-Core/tree/master/hardware/arduino/zunoG2/bootloaders). Рекомендуется выполнять загрузку бутлодера командой 
```

2022-12-26 08:27 UTC, sikmir commented on README.md
> +```
```suggestion
```sh
```

2022-12-26 08:27 UTC, sikmir commented on README.md
> +Также возможно загрузить бутлодер, указав конкретный файл
```suggestion
Также возможно загрузить бутлодер, указав конкретный файл:
```

2022-12-26 08:28 UTC, sikmir commented on README.md
> +Для просмотра информации об устройстве (PIN-кода, настроек мощности, частоты) воспользуйтесь командой
```suggestion
Для просмотра информации об устройстве (PIN-кода, настроек мощности, частоты) воспользуйтесь командой:
```

2022-12-26 08:28 UTC, sikmir commented on README.md
> +Пример вывода
```suggestion
Пример вывода:
```

2022-12-26 08:29 UTC, sikmir commented on README.md
> +Для дальнейшей работы с модулем потребуется запомнить **S2 PIN**, так как он нужен для добавления устройства в сервер. В разделе **DEVICE CFG** можно увидеть текущий режим защиты, частоту, мощность р
```suggestion
Для дальнейшей работы с модулем потребуется запомнить **S2 PIN**, так как он нужен для добавления устройства на сервер. В разделе **DEVICE CFG** можно увидеть текущий режим защиты, частоту, мощность радиосигнала (выводится в hex). 
```

2022-12-26 08:29 UTC, webconn commented
@sikmir лучше предлагать правки одним батчем, а не отдельными комментариями, а то и @ekateluv сложно следить, и уведомления сыпятся всем причастным

2022-12-26 08:30 UTC, sikmir commented on README.md
> +Для прошивки из VSCode нужно открыть основной файл ***.ino** и в верней панели нажать кнопку **"Загрузить"**.
```suggestion
Для прошивки из VSCode нужно открыть основной файл ***.ino** и в верхней панели нажать кнопку **"Загрузить"**.
```

2022-12-26 11:21 UTC, sikmir commented on .github/pull_request_template.md
> +- [ ] Поднята версия в файле changlelog
```suggestion
- [ ] Поднята версия в файле changelog
```
последняя очепятка, больше не спамлю)

2022-12-26 13:10 UTC, webconn approved these changes
Помимо предложений от @sikmir мне нечего добавить

2022-12-26 13:55 UTC, merged

2022-12-26 17:07 UTC, sikmir commented
Собрать прошивку по инструкции удалось.