Add sensors availability support
wirenboard/wb-zwave-msw pull request #8
Opened 2022-12-20 08:18 UTC by ekateluv

Исправила поддержку быстрого модбаса, добавила поддержку флагов доступности датчиков, добавила публикацию off датчика движения в случае потери связи, обновила тест-кейсы

2022-12-21 05:55 UTC, KraPete requested changes

2022-12-21 05:55 UTC, KraPete commented on TZWAVESensor.cpp
> +    if (currentAvailability == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN) {
Можно в один return объединить

2022-12-23 06:57 UTC, webconn requested changes
В довесок к комментариям от Петра

2022-12-23 06:57 UTC, webconn commented on TWBMSWSensor.h
> +    WB_MSW_SENSOR_UNKNOWN = 6
6 внезапно. В плюсах можно же `enum class` использовать, чтобы не было соблазна смешивать их с интами

2022-12-23 06:57 UTC, webconn commented on TZWAVEChannel.cpp
>      GroupIndex = groupIndex;
Кажется, теперь это всё стало откровенным бойлерплейтом, тут код почти везде одинаковый, а название методов всё ещё предполагает запись значения, хотя этого не делает.

Может, сделать один метод вроде такого?

```c++
void TZWaveChannel::SetType(uint8_t channelNumber, uint8_t groupIndex, TZWaveChannelType type)
{
  Type = type;
  ChannelNumber = channelNumber;
  GroupIndex = groupIndex;
  if (type == TZWaveChannelType::ZWAVE_CHANNEL_TYPE_CO2) {
    Autocalibration = false;
  }
}
```

2022-12-23 06:57 UTC, webconn commented on TZWAVESensor.cpp
> +            unknownSensorsLeft |= (sensorAvailability[i] == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN);
```suggestion
            unknownSensorsLeft = unknownSensorsLeft || (sensorAvailability[i] == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN);
```

2022-12-23 06:57 UTC, webconn commented on test_cases.md
> +ВНИМАНИЕ: нельзя извлекать датчик из устройства и перезагружать питание или переключать коммутатор шины! В этом случае модуль прийдет в некорректное состояние ввиду несоответствия количества зарегист
Ну строго говоря у нас датчики в MSW ведь нельзя подключать и отключать на ходу? Можно тут не расписывать всё это, а просто дописать внизу файла как ограничение на все тесты.

2022-12-23 06:57 UTC, webconn commented on test_cases.md
> +8. вставить сенсор назад, проверить что данные в канале только что извлеченного датчика стали вновь обновляться;
А это действительно должно работать? У нас это заявлено со стороны msw?

2022-12-23 06:57 UTC, webconn commented on test_cases.md
> +9. устройство исключается из интерфейса севера;
Тут подробней бы, как исключается

2022-12-23 15:12 UTC, ekateluv commented on test_cases.md
> +9. устройство исключается из интерфейса севера;
Тремя нажатиями так же. В вики есть же все...

2022-12-23 15:16 UTC, ekateluv commented on test_cases.md
> +8. вставить сенсор назад, проверить что данные в канале только что извлеченного датчика стали вновь обновляться;
Это просто проверка работоспособности модуля если устройство перестало отвечать по тем или иным причинам. Потеря связи с одним датчиком не критична, работаем дальше. Потеря модбас связи - повод начать инициализацию и сканирование модбаса сначала.
Со стороны msw это работает. Все тесткейсы, которые тут написаны, работают.

2022-12-23 15:17 UTC, ekateluv commented on TZWAVESensor.cpp
> +            unknownSensorsLeft |= (sensorAvailability[i] == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN);
А почему?

2022-12-23 15:32 UTC, ekateluv commented on test_cases.md
> +ВНИМАНИЕ: нельзя извлекать датчик из устройства и перезагружать питание или переключать коммутатор шины! В этом случае модуль прийдет в некорректное состояние ввиду несоответствия количества зарегист
Да, в реальной жизни доставать и вставлять датчики не надо. Но это здесь описано как способ имитации прекращения общения с каким либо конкретным датчиком для проверки поведения модуля.

2022-12-23 15:53 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    uint16_t availabilityFlag = 1;
Формально ситуации "не удалось прочитать" и "прочтено состояние <unknown>" это разное. Другое дело что оно сейчас работает так что реакция на эти ситуации одинаковая :) 
Там на все функции чтения чего-либо из контроллера мсв стоит возвращаемый тип bool - почему тогда это нормально?) Чтение регистров доступности датчиков это же то же самое, только адреса другие.

2022-12-25 14:27 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    uint16_t availabilityFlag = 1;
Тут так сделано, потому что потом стоит функция чтения регистра, она принимает uint16_t* как аргумент

2022-12-25 14:45 UTC, ekateluv commented on TZWAVESensor.cpp
> +    if (currentAvailability == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN) {
```suggestion
        return ((currentAvailability == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN) &&
            (WbMsw->*getAvailabilityFunction)(currentAvailability) &&
            (currentAvailability == TWBMSWSensorAvailability::WB_MSW_SENSOR_AVAILABLE));
```
?

2022-12-26 05:47 UTC, KraPete commented on TWBMSWSensor.cpp
> +    uint16_t availabilityFlag = 1;
Я про то, что 1 - это какое-то магическое число. Что оно означает?

2022-12-26 05:55 UTC, KraPete commented on test_cases.md
> +ВНИМАНИЕ: нельзя извлекать датчик из устройства и перезагружать питание или переключать коммутатор шины! В этом случае модуль прийдет в некорректное состояние ввиду несоответствия количества зарегист
Вообще ничего не понял.
Тут `датчик` - это датчик внутри msw: движение, VOC и т.п.?
Что такое `перезагружать питание` - чьё питание?
Что такое `коммутатор шины`? Это штука, которая переключает msw между разъёмом на внешний modbus и передачей данных на z-wave?
Если ты описываешь эти ситуации, значит, они могут произойти. Мой вопрос в том, как пользователь увидит `некорректное состояние`, которое ты описала? В чём оно будет выражаться?

2022-12-26 06:40 UTC, sikmir commented on TFastModbus.cpp
> +bool TFastModbus::CheckFastModbusPacket(uint8_t* packet, uint8_t packetlength)
```suggestion
bool TFastModbus::CheckFastModbusPacket(uint8_t* packet, uint8_t packetlength) const
```

2022-12-26 06:43 UTC, sikmir commented on TFastModbus.cpp
> +                                        uint8_t* modbusAddress)
```suggestion
bool TFastModbus::ParseFastModbusPacket(const uint8_t* packet,
                                        uint8_t packetlength,
                                        uint8_t* serialNumber,
                                        uint8_t* modbusAddress) const
```

2022-12-26 06:45 UTC, sikmir commented on TFastModbus.h
> +    bool CheckFastModbusPacket(uint8_t* packet, uint8_t packetlength);
```suggestion
    bool ParseFastModbusPacket(const uint8_t* packet, uint8_t packetlength, uint8_t* serialNumber, uint8_t* modbusAddress) const;
    bool CheckFastModbusPacket(const uint8_t* packet, uint8_t packetlength) const;
```

2022-12-26 06:46 UTC, sikmir commented on TWBMSWSensor.cpp
> +enum TWBMSWSensorAvailability TWBMSWSensor::ConvertAvailability(uint16_t availability)
```suggestion
enum TWBMSWSensorAvailability TWBMSWSensor::ConvertAvailability(uint16_t availability) const
```

2022-12-26 06:49 UTC, sikmir commented on TWBMSWSensor.cpp
> +bool TWBMSWSensor::GetTemperatureAvailability(enum TWBMSWSensorAvailability& availability)
```suggestion
bool TWBMSWSensor::GetTemperatureAvailability(enum TWBMSWSensorAvailability& availability) const
```

2022-12-26 06:49 UTC, sikmir commented on TWBMSWSensor.h
> +    bool GetTemperatureAvailability(enum TWBMSWSensorAvailability& availability);
```suggestion
    bool GetTemperatureAvailability(enum TWBMSWSensorAvailability& availability) const;
```

2022-12-26 06:50 UTC, sikmir commented on TWBMSWSensor.h
> +    enum TWBMSWSensorAvailability ConvertAvailability(uint16_t availability);
```suggestion
    enum TWBMSWSensorAvailability ConvertAvailability(uint16_t availability) const;
```

2022-12-26 06:51 UTC, sikmir commented on TZWAVEChannel.cpp
> +enum TZWAVEChannelState TZWAVEChannel::GetState()
```suggestion
enum TZWAVEChannelState TZWAVEChannel::GetState() const
```

2022-12-26 17:44 UTC, sikmir commented on test_cases.md
>  #Тест-кейсы
```suggestion
# Тест-кейсы

```

2022-12-26 17:44 UTC, sikmir commented on test_cases.md
> +    6.4 датчик движения будет удерживать свое прежнее значение;
```suggestion
   1. проверить, что устройство перезагрузится, отсканирует шину, обнаружит контроллер msw и войдет в рабочий режим; 
   2. проверить что количество каналов остается тем же, что и в момент добавления устройства на сервер; 
   3. проверить что каналы в сервере сохраняют свое прежнее значение до появления нового адекватного значения с датчика;
   4. датчик движения будет удерживать свое прежнее значение;
```

2022-12-26 17:44 UTC, sikmir commented on test_cases.md
> +    7.3 проверить, что в случае пропажи связи с датчиком движения, значение в его канале станет off (даже если в момент присутствия датчика было on);
```suggestion
7. достать физически из устройства какой-либо сенсор;
   1. проверить, что устройство не вернется к сканированию шины, что все каналы (кроме связанного с извлеченным датчиком) будут функционировать;
   2. канал, соответствующий извлеченному датчику, будет сохранять последнее значение;
   3. проверить, что в случае пропажи связи с датчиком движения, значение в его канале станет off (даже если в момент присутствия датчика было on);
```

2022-12-26 17:44 UTC, sikmir commented on test_cases.md
> +    9.2 канал датчика движения в момент потери связи принял значение off.
```suggestion
   1. проверить, что модуль msw вернется к состоянию сканирования шины, обнаружит контроллер msw и войдет в рабочий режим;
   2. проверить, что все каналы сохраняют свои прежние значения до получения новых данных;
   3. канал датчика движения в момент потери связи принял значение off.
```

2022-12-26 17:44 UTC, sikmir commented on test_cases.md
> +9. устройство исключается из интерфейса севера;
```suggestion
10. устройство исключается из интерфейса севера;
```

2022-12-27 16:39 UTC, ekateluv commented on test_cases.md
> +ВНИМАНИЕ: нельзя извлекать датчик из устройства и перезагружать питание или переключать коммутатор шины! В этом случае модуль прийдет в некорректное состояние ввиду несоответствия количества зарегист
Датчик - это да, конкретный датчик в мсв.
Перезагружать питание - питание у них одно на всех, основное питание мсв по проводам.
Коммутатор шины - переключатель модбас, да.
Некорректное состояние - каналы начнут обновляться непредсказуемо. Может начать скакать датчик движения.

2022-12-27 17:17 UTC, sikmir commented on TZWAVESensor.cpp
> +        zunoSendToGroupSetValueCommand(channel->GetGroupIndex(), (!inverting) ? WB_MSW_OFF : WB_MSW_ON);
```suggestion
        zunoSendToGroupSetValueCommand(channel->GetGroupIndex(), inverting ? WB_MSW_ON : WB_MSW_OFF);
```

2022-12-27 17:17 UTC, sikmir commented on TZWAVESensor.cpp
> +        {
```suggestion
    } else if ((channel.GetState() == TZWAVEChannelState::ZWAVE_CHANNEL_UNINITIALIZED) ||
            (channel.GetReportedValue() && ((currentTime - MotionLastTime) >= motionPeriod)))
    {
```

2022-12-27 17:17 UTC, sikmir commented on TZWAVESensor.cpp
> +        currentMotion >= (size_t)GetParameterValue(WB_MSW_CONFIG_PARAMETER_MOTION_THRESHOLD) ? true : false;
```suggestion
        currentMotion >= (size_t)GetParameterValue(WB_MSW_CONFIG_PARAMETER_MOTION_THRESHOLD);
```

2022-12-27 17:17 UTC, sikmir commented on TZWAVESensor.cpp
> +        zunoSendToGroupSetValueCommand(channel.GetGroupIndex(), (!inverting) ? WB_MSW_OFF : WB_MSW_ON);
```suggestion
        zunoSendToGroupSetValueCommand(channel.GetGroupIndex(), inverting ? WB_MSW_ON : WB_MSW_OFF);
```

2022-12-27 17:17 UTC, sikmir commented on TZWAVESensor.cpp
> +    uint16_t currentMotion;
Может остаться неинициализированной и далее использоваться.

2022-12-27 17:17 UTC, sikmir commented on TWBMSWSensor.h
> +    bool ReadAvailabilityRegister(enum TWBMSWSensorAvailability& availability, uint16_t registerAddress);
```suggestion
    bool ReadAvailabilityRegister(TWBMSWSensorAvailability& availability, uint16_t registerAddress);
```

2022-12-27 17:17 UTC, sikmir commented on TFastModbus.cpp
>          case 0x03:
тут бы константы тоже

2022-12-27 17:48 UTC, ekateluv commented on TWBMSWSensor.cpp
> +#define WBMSW_REG_MOTION_AVAIL 0x0175
Тут линтер мне не даст так сделать, все сдвигает

2022-12-27 17:53 UTC, ekateluv commented on TZWAVESensor.cpp
> +    uint16_t currentMotion;
При каком сценарии? Если она не прочитается или прочитается с ошибкой то там произойдет return

2022-12-27 18:28 UTC, ekateluv commented on WbMsw.h
> +#define WB_MSW_INPUT_REG_AVAILABILITY_TIMEOUT 10000 // ms
поправлено

2022-12-27 18:29 UTC, ekateluv commented on TFastModbus.cpp
> +    if (packet[0] != 0xFD || packet[1] != 0x60) {
добавила дефайны в начале файла

2022-12-27 18:29 UTC, ekateluv commented on TFastModbus.cpp
> +    uint8_t fastModbusPacket[32];
сделала дефайн

2022-12-27 18:29 UTC, ekateluv commented on TFastModbus.cpp
> +bool TFastModbus::ParseFastModbusPacket(uint8_t* packet,
поправлено

2022-12-27 18:30 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    uint16_t availabilityFlag = 1;
Убрала 1, она никакой роли не играет

2022-12-27 18:30 UTC, ekateluv commented on TWBMSWSensor.cpp
> +    } else {
убрала

2022-12-27 18:30 UTC, ekateluv commented on TZWAVESensor.cpp
> +    if (currentAvailability == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN) {
поправлено

2022-12-27 18:30 UTC, ekateluv commented on TWBMSWSensor.h
> +    WB_MSW_SENSOR_UNKNOWN = 6
сделала enum class, внесла в класс чтобы в нем лежало, где то прочитала что так делать хорошо

2022-12-27 18:31 UTC, ekateluv commented on TZWAVEChannel.cpp
>      GroupIndex = groupIndex;
Это убрала. В процедуру иницициализации канала внесла запоминание настроек канала. чтобы не писать разные функции на каждый

2022-12-27 18:31 UTC, ekateluv commented on TZWAVESensor.cpp
> +            unknownSensorsLeft |= (sensorAvailability[i] == TWBMSWSensorAvailability::WB_MSW_SENSOR_UNKNOWN);
поправила

2022-12-27 18:32 UTC, ekateluv commented on test_cases.md
> +9. устройство исключается из интерфейса севера;
дописала, чтобы сразу было видно

2022-12-27 18:32 UTC, ekateluv commented on TFastModbus.cpp
> +                                        uint8_t* modbusAddress)
добавила

2022-12-27 18:32 UTC, ekateluv commented on TFastModbus.cpp
> +bool TFastModbus::CheckFastModbusPacket(uint8_t* packet, uint8_t packetlength)
добавила

2022-12-27 18:32 UTC, ekateluv commented on TFastModbus.h
> +    bool CheckFastModbusPacket(uint8_t* packet, uint8_t packetlength);
добавила

2022-12-27 18:32 UTC, ekateluv commented on TWBMSWSensor.cpp
> +enum TWBMSWSensorAvailability TWBMSWSensor::ConvertAvailability(uint16_t availability)
добавила

2022-12-27 18:33 UTC, ekateluv commented on TWBMSWSensor.cpp
> +bool TWBMSWSensor::GetTemperatureAvailability(enum TWBMSWSensorAvailability& availability)
тут не получится, там внтури функция чтения регистра, она не дает сделать конст

2022-12-27 18:33 UTC, ekateluv commented on TWBMSWSensor.h
> +    bool GetTemperatureAvailability(enum TWBMSWSensorAvailability& availability);
тут так не получится тоже

2022-12-27 18:33 UTC, ekateluv commented on TWBMSWSensor.h
> +    enum TWBMSWSensorAvailability ConvertAvailability(uint16_t availability);
добавила

2022-12-27 18:33 UTC, ekateluv commented on TZWAVEChannel.cpp
> +enum TZWAVEChannelState TZWAVEChannel::GetState()
добавила

2022-12-27 18:34 UTC, ekateluv commented on test_cases.md
>  #Тест-кейсы
поправлено

2022-12-27 18:34 UTC, ekateluv commented on test_cases.md
> +    6.4 датчик движения будет удерживать свое прежнее значение;
поправлено

2022-12-27 18:34 UTC, ekateluv commented on test_cases.md
> +    7.3 проверить, что в случае пропажи связи с датчиком движения, значение в его канале станет off (даже если в момент присутствия датчика было on);
поправлено

2022-12-27 18:34 UTC, ekateluv commented on test_cases.md
> +    9.2 канал датчика движения в момент потери связи принял значение off.
поправлено

2022-12-27 18:34 UTC, ekateluv commented on test_cases.md
> +9. устройство исключается из интерфейса севера;
поправлено

2022-12-27 18:35 UTC, ekateluv commented on TZWAVESensor.h
> +
сделала везде enum class в объявлениях, убрала enum перед аргументами и функциями

2022-12-27 18:35 UTC, ekateluv commented on TZWAVESensor.cpp
> +        zunoSendToGroupSetValueCommand(channel->GetGroupIndex(), (!inverting) ? WB_MSW_OFF : WB_MSW_ON);
поправила

2022-12-27 18:35 UTC, ekateluv commented on TZWAVESensor.cpp
> +        {
поправила

2022-12-27 18:35 UTC, ekateluv commented on TZWAVESensor.cpp
> +        currentMotion >= (size_t)GetParameterValue(WB_MSW_CONFIG_PARAMETER_MOTION_THRESHOLD) ? true : false;
поправила

2022-12-27 18:36 UTC, ekateluv commented on TZWAVESensor.cpp
> +        zunoSendToGroupSetValueCommand(channel.GetGroupIndex(), (!inverting) ? WB_MSW_OFF : WB_MSW_ON);
поправила

2022-12-27 18:36 UTC, ekateluv commented on TWBMSWSensor.h
> +    bool ReadAvailabilityRegister(enum TWBMSWSensorAvailability& availability, uint16_t registerAddress);
убрано

2022-12-27 18:36 UTC, ekateluv commented on TFastModbus.cpp
>          case 0x03:
сделала дефайны для пакета

2022-12-28 06:04 UTC, KraPete commented on test_cases.md
> +ВНИМАНИЕ: нельзя извлекать датчик из устройства и перезагружать питание или переключать коммутатор шины! В этом случае модуль прийдет в некорректное состояние ввиду несоответствия количества зарегист
Напиши, пожалуйста, это явно, что значения будут выдаваться не в те каналы

2022-12-28 06:05 UTC, KraPete approved these changes

2022-12-29 07:30 UTC, webconn reviewed
`TZWAVEChannel` получилась попроще, но с добавлением регистра доступности всё равно получилось очень много кода. Предлагаю, однако, пока больше ничего не трогать; потом, если очень захочется, потренируемся в рефакторинге на этой штуке

2022-12-29 07:30 UTC, webconn commented on TWBMSWSensor.cpp
> +#define WBMSW_REG_NOIZE_AVAIL 0x0176
```suggestion
#define WBMSW_REG_NOISE_AVAIL 0x0176
```

2022-12-29 07:30 UTC, webconn commented on TZWAVEChannel.h
> +        ZWAVE_CHANNEL_INITIALIZED
Если уже начали использовать enum class-ы, не обязательно к каждой константе приделывать длинный префикс, он уже именем типа сформируется

2022-12-29 07:34 UTC, sikmir approved these changes

2023-01-11 12:47 UTC, closed without merging